Resources:
  osuScores:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: osu-scores
      KeySchema:
        - AttributeName: mode_user_id
          KeyType: HASH
        - AttributeName: created_at
          KeyType: RANGE
      AttributeDefinitions:
        - AttributeName: mode_user_id
          AttributeType: S
        - AttributeName: mode_user_id_beatmap
          AttributeType: S
        - AttributeName: mode_user_id_beatmap_mods
          AttributeType: S
        - AttributeName: created_at
          AttributeType: S
      GlobalSecondaryIndexes:
        - IndexName: mode_user_id_beatmap
          KeySchema:
            - AttributeName: mode_user_id_beatmap
              KeyType: HASH
            - AttributeName: created_at
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
        - IndexName: mode_user_id_beatmap_mods
          KeySchema:
            - AttributeName: mode_user_id_beatmap_mods
              KeyType: HASH
            - AttributeName: created_at
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
      BillingMode: PAY_PER_REQUEST
