Resources:  
  osuUsers:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: osu-users
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: N
      BillingMode: PAY_PER_REQUEST
