Resources:
  osuBeatmaps:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: osu-beatmaps
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: N
      BillingMode: PAY_PER_REQUEST
