Resources:
  osuBeatmapsets:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: osu-beatmapsets
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: N
      BillingMode: PAY_PER_REQUEST
