service: ost-backend
frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: "20201221"
  region: us-east-1

functions:
  graphql:
    handler: src/handlers.ost_graphql
    events:
    - http:
        path: graphql
        method: GET
        cors: true
    - http:
        path: graphql
        method: POST
        cors: true

plugins:
  - serverless-offline
  - serverless-webpack
custom:
  webpack:
    includeModules: true
