service: ost-backend
frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: "20201221"
  region: us-east-1

functions:
  graphql:
    handler: src/handlers.ost_graphql
    events:
    - http:
        path: graphql
        method: GET
        cors: true
    - http:
        path: graphql
        method: POST
        cors: true

plugins:
  - serverless-dotenv-plugin
  - serverless-webpack
  - serverless-dynamodb-local
  - serverless-offline

custom:
  webpack:
    includeModules: true
  dynamodb:
    stages:
      - dev
    start:
      port: 8000
      inMemory: true
      migrate: true
      seed: true
    seed:
      domain:
        sources:
          - table: ost-scores
            sources: [./src/database/test_data/ost-scores.json]
          - table: osu-beatmaps
            sources: [./src/database/test_data/osu-beatmaps.json]
          - table: osu-beatmapsets
            sources: [./src/database/test_data/osu-beatmapsets.json]
          - table: osu-users
            sources: [./src/database/test_data/osu-users.json]
    migration:
      dir: offline/migrations

resources:
  Resources:
    ostScores:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ost-scores
        AttributeDefinitions:
          - AttributeName: user_id
            AttributeType: N
          - AttributeName: created_at
            AttributeType: S
        KeySchema:
          - AttributeName: user_id
            KeyType: HASH
          - AttributeName: created_at
            KeyType: RANGE
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
    osuBeatmaps:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: osu-beatmaps
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: N
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
    osuBeatmapsets:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: osu-beatmapsets
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: N
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
    osuUsers:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: osu-users
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: N
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
